### ISSUE TITLE
Repeated hyperedges are not merged and transformed in weighted hyperedges

### ISSUE THREAD

**Issue by mcontisc** [ComplexGroupInteractions/xgi#196] opened 2022-10-14 08:21 UTC
When I create the hypergraph 
```
H = xgi.Hypergraph([[1, 2], [1, 2], [1, 2, 4]])
```
the hyperedge (1, 2) is considered twice in the incidence matrix, even if it is recognized to be duplicated by running `duplicate_edges()`. 

Similarly, the hypergraph 
```
H = xgi.Hypergraph([[1, 2], [2, 1], [1, 2, 4]])
```
considers the hyperedge (1, 2) different from (2, 1) and it will create two different columns in the incidence matrix. This time, it is not recognized to be duplicated.

In my experience, I would consider the hyperedge (1, 2) once with weight 2 for both cases.

Thus, is this a desired feature of the class or a bug in the code?

**Comment by maximelucas** [comment] 2022-10-14 09:31
Thanks for this. 

First, it is by design that, so far, we keep [1,2] represented twice in `H.edges`. We're discussing how to implement a "merge" function that would allowed to end up with one edge with weight 2 as you suggest (see #163). I think we keep them separate by default because merging in general can be done in different ways especially when different attributes are involved. 

Still, I see two potential problems in what you show:
1. first case, it does seem odd to have [1,2] represented twice in the incidence matrix. We should discuss if we really intended this. I'll let the others comments on this too.
2. second case, I'm more surprised that this happens. I cannot reproduce it either, I suspect you're not using the latest version?

Talking about versions, in the latest v0.4.3, `H.duplicate_edges()` is now `H.edges.duplicates()`.

**Comment by mcontisc** [comment] 2022-10-14 09:45
Thank you, I actually did not see #163. This is precisely what I meant, sorry.

1. To be more precise, I meant this:
```
>> H = xgi.Hypergraph([[1, 2], [1, 2], [1, 2, 4]])
>> xgi.linalg.incidence_matrix(H).toarray()
array([[1, 1, 1],
       [1, 1, 1],
       [0, 0, 1]])

**Comment by maximelucas** [comment] 2022-10-14 09:58
No worries, it's hard to keep track for anyone :) 

1. Yes absolutely I understand your point. And I'm not sure if this current behaviour for the incidence matrix is something we want. Because it then gets propagated to other linalg functions that use it, such as the Laplacian matrices etc. Worth thinking about. 
2. Great!

(pro tip: `xgi.incidence_matrix(H)`is the same as `xgi.linalg.incidence_matrix(H)` if you want a slightly shorter version.)

**Comment by mcontisc** [comment] 2022-10-14 10:02
Alright :) Then looking forward to further discussions regarding point 1.

**Comment by leotrs** [comment] 2022-10-14 10:19
This is a great find. If I understand correctly, the problem is what do we do with the incidence matrix when we have repeated edges. A few thoughts:

1. If an edge is repeated twice, it should create two rows/columns in the incidence matrix. That's why we refer to the edges by ID and not by member list. Moreover, the incidence matrix should always have as many rows (columns?) as there are edges.
2. After we merge duplicate edges, we should give the user the chance to obtain the weighted or unweighted versions of the incidence matrix.

**Comment by maximelucas** [comment] 2022-10-27 08:26
Point 1. is what we currently do. I was just worried that this create problems when computing `xgi.laplacian()` and other linalg functions because they use `xgi.incidence_matrix()`. But `xgi.laplacian()` has dimension NxN, so it already collapses everything onto nodes and I think there is no problem there: using Martina's example we get
```python
>> xgi.laplacian(H, order=1)
array([[ 2., -2.,  0.],
       [-2.,  2.,  0.],
       [ 0.,  0.,  0.]])
```
My feeling is that this issue can be closed as the remaining question about merging is being discussed in #163 ?

**Comment by leotrs** [comment] 2022-10-27 12:40
Yeah there should be no problem with the Laplacian. Perhaps adding a test involving the Laplacian in the case of repeated edges would be nice.

> My feeling is that this issue can be closed as the remaining question about merging is being discussed in https://github.com/ComplexGroupInteractions/xgi/issues/163 ?

Moving to #163

**Closed by leotrs** 2022-10-27 12:40 UTC
